### ISSUE TITLE
Add question for version of CNS and resulting inventory file options

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/openshift-cic#16] opened 2018-06-19 17:43 UTC
Need to add a question for what version of CNS is to be deployed. This is needed because by default OCP deploys the CNS image files with tag = latest.

Add question
What version of CNS are you deploying? 3.9
```
# Container image to use for glusterfs pods
openshift_storage_glusterfs_image=rhgs-server-rhel7
openshift_storage_glusterfs_version=v3.9

# Container image to use for glusterblock-provisioner pod
openshift_storage_glusterfs_block_image=rhgs-gluster-block-prov-rhel7
openshift_storage_glusterfs_block_version=v3.9

# Container image to use for heketi pods
openshift_storage_glusterfs_heketi_image=rhgs-volmanager-rhel7
openshift_storage_glusterfs_heketi_version=v3.9
```

**Comment by netzzer** [comment] 2018-06-20 19:34
Would be good to include registry path in image 
```
# Container image to use for glusterfs pods
openshift_storage_glusterfs_image=registry.access.redhat.com/rhgs3/rhgs-server-rhel7
openshift_storage_glusterfs_version=v3.9

# Container image to use for glusterblock-provisioner pod
openshift_storage_glusterfs_block_image=registry.access.redhat.com/rhgs3/rhgs-gluster-block-prov-rhel7
openshift_storage_glusterfs_block_version=v3.9

# Container image to use for heketi pods
openshift_storage_glusterfs_heketi_image=registry.access.redhat.com/rhgs3/rhgs-volmanager-rhel7
openshift_storage_glusterfs_heketi_version=v3.9
```

**Comment by ramkrsna** [comment] 2018-07-12 15:10
The Issue is now merged

**Closed by ramkrsna** 2018-07-12 15:10 UTC
